API:
  REST:
    ENABLE: TRUE
    TYPE: HTTP
    PORT: 80
  CLI:
    TYPE: [SSH,TELNET] # SSH,TELNET
    PORTS:
      SSH: 22
      TELNET: 53
LOGGING:
  LEVEL: DEBUG  # DEBUG/INFO
DEBUG_ENABLED: FALSE  # TRUE/FALSE
DRIVER:
  VLAN_MIN: 100
  VLAN_MAX: 4000
  MAP_ON_SET_VLAN: FALSE  # If True, actual Mapping process is called only when vlanId set for both ports